{
 "title": "Bitcoin BigQuery Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Liczba transakcji w czasie (na godzinę)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP_TRUNC(block_timestamp, HOUR) as time, count(*) as transactions FROM `${project_id}.dbt_prod.bitcoin_transactions` WHERE $__timeFilter(block_timestamp) GROUP BY 1 ORDER BY 1"
    }
   ]
  },
  {
   "title": "Średnia opłata (Fee)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(fee) as avg_fee FROM `${project_id}.dbt_prod.bitcoin_transactions` WHERE $__timeFilter(block_timestamp)"
    }
   ]
  },
  {
   "title": "Ostatnie Transakcje",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT block_timestamp, block_number, `hash`, size, fee FROM `${project_id}.dbt_prod.bitcoin_transactions` WHERE $__timeFilter(block_timestamp) ORDER BY block_timestamp DESC LIMIT 100"
    }
   ]
  }
 ]
}